server:
  port: 8090
spring:
  application:
    name: hld-wms
  datasource:
    url: jdbc:mysql://120.27.120.58:3306/report?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: report
    password: report

    #url: jdbc:mysql://localhost:3306/hld?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: hengfeng
    #password: hengfeng
  redis:
    host: 120.27.120.58
    port: 6379
    password: hld
  jpa:
    show-sql: true
#    password:
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 日志配置
bingove:
  logback:
    path: /home/wms/app/logs
#    path: /data/app/logs
logging:
  config: classpath:logback-spring.xml
  level:
    com.example.project.demos.web.dao: debug