server:
  port: 8090
spring:
  application:
    name: hld-wms
  datasource:
    url: jdbc:mysql://120.27.120.58:3306/report?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: report
    password: report

    #url: jdbc:mysql://localhost:3306/hld?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: hengfeng
    #password: hengfeng
  redis:
    database: 0       # Redis数据库索引（默认为0）
    host: 120.27.120.58
    port: 6379
    password: hld
  jpa:
    show-sql: true
  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区
  #上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
#    password:
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 日志配置
bingove:
  logback:
    path: /home/wms/app/logs
#    path: /data/app/logs
logging:
  config: classpath:logback-spring.xml
  level:
    com.example.project.demos.web.dao: debug

#上传文件路径
upload:
  filePath: /home/wms/app/uploadFiles/

#token过期时间 单位：分钟
token:
  expir: 5

